#!/bin/sh

ELASTICSEARCH_TYPE=${ELASTICSEARCH_TYPE:-elasticsearch}
ELASTICSEARCH_AWS_REGION=${ELASTICSEARCH_AWS_REGION:-'no-region-specified'}


ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-es-logging.default.svc}
ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT:-9200}
ELASTICSEARCH_SCHEME=${ELASTICSEARCH_SCHEME:-http}

FLUENTD_FLUSH_INTERVAL=${FLUENTD_FLUSH_INTERVAL:-10s}
FLUENTD_FLUSH_THREADS=${FLUENTD_FLUSH_THREADS:-1}
FLUENTD_RETRY_LIMIT=${FLUENTD_RETRY_LIMIT:-10}
FLUENTD_DISABLE_RETRY_LIMIT=${FLUENTD_DISABLE_RETRY_LIMIT:-true}
FLUENTD_RETRY_WAIT=${FLUENTD_RETRY_WAIT:-1s}
FLUENTD_MAX_RETRY_WAIT=${FLUENTD_MAX_RETRY_WAIT:-60s}
FLUENTD_BUFFER_CHUNK_LIMIT=${FLUENTD_BUFFER_CHUNK_LIMIT:-8m}
FLUENTD_BUFFER_QUEUE_LIMIT=${FLUENTD_BUFFER_QUEUE_LIMIT:-8192}
FLUENTD_BUFFER_TYPE=${FLUENTD_BUFFER_TYPE:-memory}
FLUENTD_BUFFER_PATH=${FLUENTD_BUFFER_PATH:-/var/fluentd/buffer}
FLUENTD_LOGSTASH_FORMAT=${FLUENTD_LOGSTASH_FORMAT:-true}

mkdir /etc/fluent

cat << 'EOF' > /etc/fluent/fluent.conf
<source>
  type tail
  path /var/log/containers/*.log
  pos_file /var/log/fluentd-position/es-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S.%N
  tag kubernetes.*
  format json
  read_from_head true
  keep_time_key true
</source>

<filter kubernetes.**>
  type kubernetes_metadata
</filter>

<match **>
EOF

cat << EOF >> /etc/fluent/fluent.conf
  type ${ELASTICSEARCH_TYPE}
  log_level info
  include_tag_key true
  time_key time
EOF

if [ ${ELASTICSEARCH_TYPE} == "elasticsearch" ];then
    cat << EOF >> /etc/fluent/fluent.conf
  host ${ELASTICSEARCH_HOST}
  port ${ELASTICSEARCH_PORT}
EOF
elif [ ${ELASTICSEARCH_TYPE} == "aws-elasticsearch-service" ];then
    cat << EOF >> /etc/fluent/fluent.conf
  <endpoint>
    url ${ELASTICSEARCH_HOST}
    region ${ELASTICSEARCH_AWS_REGION}
    $([ -n "${ELASTICSEARCH_AWS_ACCESS_KEY}" ] && echo access_key_id ${ELASTICSEARCH_AWS_ACCESS_KEY})
    $([ -n "${ELASTICSEARCH_AWS_SECRET_KEY}" ] && echo secret_access_key ${ELASTICSEARCH_AWS_SECRET_KEY})
  </endpoint>
EOF
else
    echo "Unsupported ELASTICSEARCH_TYPE=${ELASTICSEARCH_TYPE}"
    exit 1
fi

cat << EOF >> /etc/fluent/fluent.conf
  scheme ${ELASTICSEARCH_SCHEME}
  $([ -n "${ELASTICSEARCH_USER}" ] && echo user ${ELASTICSEARCH_USER})
  $([ -n "${ELASTICSEARCH_PASSWORD}" ] && echo password ${ELASTICSEARCH_PASSWORD})
  buffer_type ${FLUENTD_BUFFER_TYPE}
  $([ "${FLUENTD_BUFFER_TYPE}" == "file" ] && echo buffer_path ${FLUENTD_BUFFER_PATH})
  buffer_chunk_limit ${FLUENTD_BUFFER_CHUNK_LIMIT}
  buffer_queue_limit ${FLUENTD_BUFFER_QUEUE_LIMIT}
  flush_interval ${FLUENTD_FLUSH_INTERVAL}
  retry_limit ${FLUENTD_RETRY_LIMIT}
  $([ "${FLUENTD_DISABLE_RETRY_LIMIT}" == "true" ] && echo disable_retry_limit)
  retry_wait ${FLUENTD_RETRY_WAIT}
  max_retry_wait ${FLUENTD_MAX_RETRY_WAIT}
  num_threads ${FLUENTD_FLUSH_THREADS}
  logstash_format ${FLUENTD_LOGSTASH_FORMAT}
EOF

cat << 'EOF' >> /etc/fluent/fluent.conf
</match>
EOF

exec je fluentd
